FROM knowagelabs/knowage-server-docker:8.2-SNAPSHOT

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV KEYSTORE_PATH ${JAVA_HOME}/jre/lib/security/cacerts
ENV TRUSTSTORE_PASS {{ config['keystore']['password'] }}

COPY {{ config['keystore']['cert_path'] }} /tmp/cas.crt

RUN echo "Importing CAS Certificates into Knowage Truststore" && \
    ${JAVA_HOME}/bin/keytool -import -trustcacerts -noprompt \
    -alias cas_server_cert \
    -file /tmp/cas.crt \
    -keystore ${KEYSTORE_PATH} \
    -storepass ${TRUSTSTORE_PASS} && \
    echo "Certificate imported successfully"

RUN  rm /tmp/cas.crt